### ISSUE TITLE
NullPointer on sanitizeMultilineText

### ISSUE THREAD

**Issue by Im2be** [geheur/watson-master-clue-tracker#10]
2022-08-14 22:10:16 [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at net.runelite.client.util.Text.sanitizeMultilineText(Text.java:146)
	at com.watsoncluetracker.WatsonPlugin.optionSelected(WatsonPlugin.java:153)
	at com.watsoncluetracker.NpcDialogTracker.optionSelected(NpcDialogTracker.java:254)
	at com.watsoncluetracker.NpcDialogTracker.onScriptPostFired(NpcDialogTracker.java:226)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.post(Hooks.java:179)
	at client.kn(client.java:23495)
	at hh.q(hh.java:7290)
	at y.o(b.java:116)
	at client.fd(client.java:3469)
	at client.aj(client.java:1069)
	at as.dh(as.java:359)
	at as.run(as.java:338)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by geheur** [comment]
Obsolete, the code that caused this error no longer exists.
